# Generated by Django 5.1.2 on 2025-05-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_thumnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
